---
- hosts: erp
  become: yes
  become_method: su
  tasks:
  - name: Verify build_number is set
    assert:
      that: 
        - "build_number > 0"

  - name: Package Prerequisites
    apt:
      update_cache: yes
      cache_valid_time: 86400
      pkg: "{{item}}"
    with_items:
      - git
      - python-pip
      - daemon

  - name: Clone test-definitions repository
    git:
      repo: 'https://git.linaro.org/qa/test-definitions.git'
      dest: /root/test-definitions
      version: master

  - name: Install python prerequisites
    pip:
      requirements: /root/test-definitions/automated/utils/requirements.txt

  - name: Install python prerequisites
    pip:
      name: python-slugify

  - name: Copy test harness
    copy:
      src: run_erp_suite.sh
      dest: /root/run_erp_suite.sh
      mode: 0755

  - name: Run ERP test suite
    # daemon --name ensures only one runs at a time
    command: daemon --name=erp_suite --errlog=/root/run_erp_suite.stderr.log --dbglog=/root/run_erp_suite.stdout.log -- /root/run_erp_suite.sh {{build_number}}
    environment:
      SQUAD_AUTH_TOKEN: "{{squad_auth_token}}"

